#This program builds a "Normalize" function
#The function Normalize will be used to normalize inconsistent data

# Build your own `normalize()` function
MLnormalizefun <- function(x) {
  num <- x - min(x)
  denom <- max(x) - min(x)
  return (num/denom)
}
